### ISSUE TITLE
Add basic installation instructions for QP solvers to the docs

### ISSUE THREAD

**Issue by jfoldi81** [micom-dev/micom#13]
I'm trying to run com.cooperative_tradeoff on a community using some sbml files but cannot because I'm using the default GLPK and don't know how to use IBM Cplex instead. I downloaded it as an academic edition but do not know how to set it as the solver for micom. Thanks in advance!

**Comment by cdiener** [comment]
The following section from the q2-micom docs may be helpful: https://micom-dev.github.io/q2-micom/#install-a-qp-solver .

**Comment by jfoldi81** [comment]
Thank you so much! I hadn't seen that page before and now have it working.

**Comment by cdiener** [comment]
Awesome. I'll add those instructions to the micom docs as well.

**Comment by cdiener** [comment]
closing in favour of #43
