### ISSUE TITLE
Increase the number of threads for grow for a single model

### ISSUE THREAD

**Issue by PathogeNish** [micom-dev/micom#161]
### Checklist

- [x] There are [no similar issues or pull requests](https://github.com/micom-dev/micom/issues) for this yet.
- [x] The request is *not* specific for MICOM Qiime 2 plugin (q2-micom)

### Is your feature related to a problem? Please describe it.

I want to be able to increase the number of threads allowed in the  _grow_ function. It seems that the number of threads assigned to the growth of a single model (community model from a single sample) is fixed at 1. The _threads_ option is used only when the model folder has multiple models.

## Describe the solution you would like.

Since the _grow_ function can take upto 20 minutes for a solver to converge on a solution, I would like to be able to parallelise the grow process for individual models in order to speed up solve time and optimise system usage since running a single model engages only 1 thread, leaving the others unused.

**Comment by cdiener** [comment]
In theory it is possible for some solvers (like CPLEX or GUROBI) by changing the parameters of the solver itself but single model FBA can not be parallelized very efficiently so wou would not see much gains there. If a single model takes that long it might be an issue with the solver. This should be fast with CPLEX or Gurobi.

**Comment by PathogeNish** [comment]
Understood. Thanks @cdiener! 😄

**Comment by PathogeNish** [comment]
Understood. Thanks @cdiener! 😄
