### ISSUE TITLE
interpretation of plot_exchanges_per_sample default behavior

### ISSUE THREAD

**Issue by mmp3** [micom-dev/micom#38]
The "[Plotting consumed metabolites](https://micom-dev.github.io/micom/viz.html#Plotting-consumed-metabolites)" section of the documentation describes the function `plot_exchanges_per_sample` with default parameter `direction='import'` as plotting the metabolites _consumed_ by the microbial community.

In the source code for `plot_exchanges_per_sample`, the subset with `taxon='medium`' is selected. But isn't the "import" for the `'medium'` actually the _export_ for the microbial community? This seems at odds with the description of `plot_exchanges_per_sample(direction='import')` as plotting the _consumption_ patterns of the microbes.

Perhaps I am misinterpreting the `direction` of the fluxes for the `'medium`' in the output of the `grow` function?

**Comment by cdiener** [comment]
Metabolites can enter the extracellular space either via (1) production by microbes or by (2) diffusion into the extracellular space from the environment (coming from food components or the host). `plot_exchanges_per_sample(..., direction='import')` denotes (2). Case (1) is called "production flux" in MICOM and is used for the phenotype prediction for instance.

**Comment by mmp3** [comment]
Very helpful, thank you.
Is Case (2) the interpretation of `plot_exchanges_per_sample(..., direction='export')` ?

**Comment by cdiener** [comment]
Case 2 is direction="import". Here import just means things coming into the system. Maybe not the best term since it makes it sound like an active process and not the passive diffusion that it is.

**Comment by mmp3** [comment]
Pardon my typo, I meant to ask if Case (1) is the interpretation of `plot_exchanges_per_sample(..., direction='export')`, which from your response I take to be 'yes'?

**Comment by cdiener** [comment]
Yep pretty much, direction="export" gives you production_by_microbes - readsorption_by_microbes. When we talk about "production fluxes" in MICOM we mean only the production_by_microbes part regardless of the readsorption.

**Comment by cdiener** [comment]
Closing for now. Feel free to open a [discussion topic](https://github.com/micom-dev/micom/discussions) if there are more questions :+1:
